# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Week4' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Floaty', '~> 4.2.0'
  pod 'CVCalendar', '~> 1.7.0'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Kingfisher', '~> 6.0'
  pod 'Cosmos', '~> 23.0'

  # Pods for Week4

end
